version: '2'
services: 
    backend:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8000:8000
      volumes: 
        - .:/choozenREST
      depends_on:
        - db

    db:
      image: mysql:5.7.36
      restart: always
      environment:
        MYSQL_DATABASE: choozen
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - .dbdata:/var/lib/mysql
      ports:
        - 33066:3306