# Generated by Django 3.2.9 on 2022-04-25 12:43

from django.db import migrations

def create_member_levels(apps, schema_editor):
  member_levels = [
    5,
    10,
    20,
    50,
    100
  ]
  Data = apps.get_model('choozen', 'MemberLevel')
  for ml in member_levels:
    Data.objects.create(number_members_per_group=ml)

def delete_member_levels(apps, schema_editor):
  Data = apps.get_model('choozen', 'MemberLevel')
  Data.objects.all().delete()

def create_group_level(apps, schema_editor):
  group_levels = [
    5,
    10,
    20,
    50,
    100
  ]
  Data = apps.get_model('choozen', 'GroupLevel')
  for gl in group_levels:
    Data.objects.create(number_of_groups=gl)

def delete_group_level(apps, schema_editor):
  Data = apps.get_model('choozen', 'GroupLevel')
  Data.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('choozen', '0004_grouplist_memberlevel'),
    ]

    operations = [
      migrations.RunPython(create_member_levels, delete_member_levels),
      migrations.RunPython(create_group_level, delete_group_level),
    ]