# Generated by Django 3.2.9 on 2022-01-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
