# Generated by Django 3.2.9 on 2022-03-03 14:50

from django.db import migrations
from choozen.models import Genre

def create_genre(apps, schema_editor):
  genre = [
    'Action',
    'Adventure',
    'Animation',
    'Biography',
    'Comedy',
    'Crime',
    'Documentary',
    'Drama',
    'Family',
    'Fantasy',
    'Film-Noir',
    'Game-Show',
    'History',
    'Horror',
    'Music',
    'Musical',
    'Mystery',
    'News',
    'Reality-TV',
    'Romance',
    'Sci-Fi',
    'Short',
    'Sport',
    'Superhero',
    'Talk-Show',
    'Thriller',
    'War',
    'Western'
  ]
  Data = apps.get_model('choozen', 'Genre')
  for g in genre:
    Data.objects.create(type=g)

def delete_genre(apps, schema_editor):
  Data = apps.get_model('choozen', 'Genre')
  Data.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('choozen', '0001_initial'),
    ]

    operations = [
      migrations.RunPython(create_genre, delete_genre),
    ]