# Generated by Django 3.2.9 on 2022-01-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choozen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
