# Generated by Django 3.2.9 on 2022-03-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choozen', '0002_auto_20220303_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
