# Generated by Django 3.2.9 on 2022-02-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choozen', '0003_directed_genre_hasgenre_person_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
