# Generated by Django 3.2.9 on 2022-04-25 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choozen', '0005_auto_20220425_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='choozen.grouplevel'),
        ),
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('member_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='choozen.memberlevel')),
            ],
        ),
        migrations.CreateModel(
            name='IsFriendWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
