# Generated by Django 3.2.9 on 2022-04-26 09:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choozen', '0006_auto_20220425_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsPartOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creator', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choozen.grouplist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='HasReviewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choozen.movie')),
                ('partOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choozen.ispartof')),
            ],
            options={
                'unique_together': {('partOf', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='HasProposed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_watched', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choozen.movie')),
                ('partOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choozen.ispartof')),
            ],
            options={
                'unique_together': {('partOf', 'movie')},
            },
        ),
    ]
