# Generated by Django 3.2.9 on 2022-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choozen', '0007_hasproposed_hasreviewed_ispartof'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtimeStr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
